version: "3.8"
services:
  app:
    build: .
    ports:
      - 3200:3200
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres:10.16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
